xbindkeys

sh ~/Objects/scripts/bat_warning.sh &

xss-lock -- i3lock -i /home/ssn/Objects/mountain.png &

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xnit/xinitrc.d/*; do 
    [ -x "$f" ] && . "$f" 
  done 
  unset f 
fi 

exec i3 -V >> ~/.i3/i3log 2>&1
